### ISSUE TITLE
是否考虑放一个blog内容示例

### ISSUE THREAD

**Issue by Nanmen** [gaowei-space/markdown-blog#10]
是否考虑放一个blog内容示例，现在是有个blog地址示例，想看下文件目录以及关联的写法

**Comment by gaowei-space** [comment]
内容示例是指目录结构吗？

我的[博客](https://blog.gaowei.tech)目录结构是这样的
<img width="547" alt="image" src="https://user-images.githubusercontent.com/10205742/203467452-64e71536-7ce5-429e-bd5d-e7c45c1a4dd0.png">

`md` 文件夹存放的是所有 Markdown 文件，目录如图：
<img width="578" alt="image" src="https://user-images.githubusercontent.com/10205742/203467712-c2f92274-7b86-4644-8fee-e165161941a6.png">

和md同一级目录放置解压后的 markdown-blog 运行程序，执行  `./markdown-blog web` 就启动了，如果调试的话可以执行 `./markdown-blog web -e dev`

不确定是否解答了你的疑惑😅

**Comment by Nanmen** [comment]
我试试，因为我建立了个主页.md ，在首页加了个toc，然后渲染的有点问题，于是想问问

**Comment by Alafun** [comment]
![image](https://user-images.githubusercontent.com/78416589/204313110-cd97d9c7-f839-43eb-8ad4-a75052f21414.png)

**Comment by Alafun** [comment]
![image](https://user-images.githubusercontent.com/78416589/204314631-f7b67df3-27fd-4bda-8e18-9f3ef70d1e00.png)
不知道为什么xftp里面汉字编码和命令行里面编码不一样
![image](https://user-images.githubusercontent.com/78416589/204314891-28fd16b1-ea99-47b3-8e15-634bbff6914b.png)

**Comment by gaowei-space** [comment]
xftp 不用这个，或者看看这个软件是否有设置字符集的地方，改为utf8 @Alafun

**Comment by Alafun** [comment]
> xftp 不用这个

![image](https://user-images.githubusercontent.com/78416589/204447174-99f64c94-2549-4396-93cd-c8e204d18793.png)

**Comment by gaowei-space** [comment]
@Nanmen  暂时关闭了噢，如果使用过程中还有其他问题，可以到 https://github.com/gaowei-space/markdown-blog/discussions 发起讨论噢
