### ISSUE TITLE
编码相关问题(单独开了一个issue

### ISSUE THREAD

**Issue by Alafun** [gaowei-space/markdown-blog#13]
![image](https://user-images.githubusercontent.com/78416589/204447705-19e70a36-46e8-41a9-91bb-691982a69e4a.png)
![image](https://user-images.githubusercontent.com/78416589/204448136-6faa5c45-c209-45c9-b443-df4227ed6bc6.png)

通过在xshell里面尝试修改几个主流的字符集, 感觉就utf-8编码方式支持的最好(`ls`可以正常显示, 但是`tree`命令显示不是很正常, 并且网站上也正常显示. )

**Comment by gaowei-space** [comment]
看描述的内容，是不是和博客程序没啥关系呐？🤓

**Comment by Alafun** [comment]
确实
