### ISSUE TITLE
是否可以仿照typora出一个outline

### ISSUE THREAD

**Issue by Alafun** [gaowei-space/markdown-blog#14]
![image](https://user-images.githubusercontent.com/78416589/204457990-f7a5a1ae-c9af-42bd-b964-13da49a9d1a9.png)
就像这样👆
好像对[TOC]和表格的支持还需要维护
![image](https://user-images.githubusercontent.com/78416589/204458795-c32450c2-fbbd-49c9-97d1-fb18f27b328f.png)
![image](https://user-images.githubusercontent.com/78416589/204458824-fbe7c4ad-fb47-4d09-8c3e-f32f3b613fac.png)

**Comment by gaowei-space** [comment]
- [toc] 目前支持小写的方式，新版本优化下不区分大小写
- 表格也是支持的，写法如下：
title1 | title2
-------- | ------
data1 | data2 
- outline 使用场景好像没有那么多噢~

**Comment by Alafun** [comment]
好耶

**Comment by Alafun** [comment]
我想的是这个outline可以承担toc的一部分功能
