### ISSUE TITLE
我感觉有BUG现在样式又丢了什么都没做 按刚刚那样来也不行了

### ISSUE THREAD

**Issue by HskGo** [gaowei-space/markdown-blog#2]

**Comment by gaowei-space** [comment]
assets 是需要在 web 目录的噢

**Comment by gaowei-space** [comment]
哎呀，你这问题还挺难复现的哈，我这边试试复现下，才能定位问题出在哪

**Comment by gaowei-space** [comment]
前端小伙伴在路上了，下周会提个PR，哈哈...

**Comment by gaowei-space** [comment]
你是做什么开发的？可以一起参与开发一下啊

**Comment by gaowei-space** [comment]
阔以阔以，我也主后端，好久没撸过前端了

**Comment by gaowei-space** [comment]
> 我现在的解决方案就是在cp一个assets重命名为static放到根目录下就能解决样式问题
> 
> 如果按你官网所说的方式安装 机会找不到样式 有时候又没问题 就我第一次反馈的时候 我就试了N次了 结果突然就好了 我出去一趟回来 又不行了
> 
> 你有空可以排查一下看看 这是我现在的解决方案

对了，你本地环境有问题么？

**Comment by gaowei-space** [comment]
当前部署是在什么系统环境？

**Comment by gaowei-space** [comment]
1. 开发模式运行，看看能从报错上发现啥问题不：
```
./markdown-blog web -e dev
```
2. 浏览器调试看看请求的路径是下面这样吧
<img width="902" alt="image" src="https://user-images.githubusercontent.com/10205742/179352845-5e67a956-aa3b-40fb-a855-c1993b67d3df.png">

**Comment by gaowei-space** [comment]
![IMG_8949](https://user-images.githubusercontent.com/10205742/179353326-b968cdab-0901-43ce-ac90-1eba1e317ab6.PNG)

👆
