### ISSUE TITLE
md中的本地图片应当如何显示？

### ISSUE THREAD

**Issue by rainote2020** [gaowei-space/markdown-blog#33]
我使用typora编辑md文件时，使用相对路径插入图片能够正常显示。
无论使用md语法，如：
`![img](./pic/image-20230404195402327.png)`
还是html语法，如：
<img src="pic/image-20230404195402327.png" alt="image-20230404195402327" style="zoom:67%;" />
都可以在typora及其他本地编辑器中正常显示，证明md语法及路径是无误的。

按照同样的路径上传至blog内容目录后，文字正常，图片全部不能正常显示。如图所示：
![image](https://user-images.githubusercontent.com/61146508/230566256-fd2e19ba-ea69-49d2-a365-1d3b620fbcd7.png)
请问是markdownblog不支持本地图片。还是我md中图片的路径写法有问题。

**Comment by gaowei-space** [comment]
@rainote2020  在计划中，下个版本会支持 🤝

**Comment by gaowei-space** [comment]
多谢反馈，下个版本会支持读取本地图片~
________________________________
发件人: rainote2020 ***@***.***>
发送时间: 2023年4月7日 15:49
收件人: gaowei-space/markdown-blog ***@***.***>
抄送: Subscribed ***@***.***>
主题: [gaowei-space/markdown-blog] md中的本地图片应当如何显示？ (Issue #33)


我使用typora编辑md文件时，使用相对路径插入图片能够正常显示。
无论使用md语法，如：
![img](./pic/image-20230404195402327.png)
还是html语法，如：
[image-20230404195402327]<pic/image-20230404195402327.png>
都可以在typora及其他本地编辑器中正常显示，证明md语法及路径是无误的。

按照同样的路径上传至blog内容目录后，文字正常，图片全部不能正常显示。如图所示：
[image]<https://user-images.githubusercontent.com/61146508/230566256-fd2e19ba-ea69-49d2-a365-1d3b620fbcd7.png>
请问是markdownblog不支持本地图片。还是我md中图片的路径写法有问题。

―
