### ISSUE TITLE
建议-可否仅显示目录下md后缀名的文件

### ISSUE THREAD

**Issue by xtay573269555** [gaowei-space/markdown-blog#34]
小而美的东西确实简洁好用。

我现在的markdown目录下有原始的md文件，还有通过Typora导出的同名pdf文件。目前程序将目录下的所有文件都列出来了，可否在显示时，仅显示md后缀名的文件。谢谢

**Comment by gaowei-space** [comment]
收到，我看看

**Comment by gaowei-space** [comment]
> 小而美的东西确实简洁好用。
> 
> 我现在的markdown目录下有原始的md文件，还有通过Typora导出的同名pdf文件。目前程序将目录下的所有文件都列出来了，可否在显示时，仅显示md后缀名的文件。谢谢

新版本根据你的建议，排除了非MD文件 ✌️
