### ISSUE TITLE
favicon.ico无法正常读取

### ISSUE THREAD

**Issue by dianso** [gaowei-space/markdown-blog#39]
已解决

需要把资源文件夹放到MD目录。

还有个问题：

目前的favicon.ico无法正常读取，解决办法是。

将本地的markdown-blog/favicon.ico装载/favicon.ico即可。

**Comment by dianso** [comment]
目前的favicon.ico无法正常读取，解决办法是。

将本地的markdown-blog/favicon.ico装载/favicon.ico即可。

加载文件是在哪个目录啊？

/static吗？

**Comment by dianso** [comment]
我在docker里面'--fdir' 'assets'

指定了assets文件夹，放到和md同一级的文件夹，可是读取不了。

**Comment by dianso** [comment]
顺便期待支持：

自定义夜间白天模式，觉得白天模式好看点。

自定义文章宽度

自定义左侧导航栏宽度

页面标题动态显示为文章名称

**Comment by gaowei-space** [comment]
> 顺便期待支持：
> 
> 自定义夜间白天模式，觉得白天模式好看点。
> 
> 自定义文章宽度
> 
> 自定义左侧导航栏宽度
> 
> 页面标题动态显示为文章名称

1
