### ISSUE TITLE
作者你好，请问access.log日志文件如何关闭啊？

### ISSUE THREAD

**Issue by dianso** [gaowei-space/markdown-blog#44]
作者你好，请问access.log日志文件如何关闭啊？

cache/logs/ 每天都会生成log文件，有时候访问量高了几百M

如何关闭日志功能呀？

**Comment by gaowei-space** [comment]
当前在 prod 模式会记录精简的访问日志，暂未支持关闭。建议配置日志管理，比如 Linux 中的 logrotate

**Comment by gaowei-space** [comment]
> 作者你好，请问access.log日志文件如何关闭啊？
> 
> cache/logs/ 每天都会生成log文件，有时候访问量高了几百M
> 
> 如何关闭日志功能呀？

方便分享下你的博客地址不，看看有哪些有意思的内容~

**Comment by dianso** [comment]
> > 作者你好，请问access.log日志文件如何关闭啊？
> > cache/logs/ 每天都会生成log文件，有时候访问量高了几百M
> > 如何关闭日志功能呀？
> 
> 方便分享下你的博客地址不，看看有哪些有意思的内容~

啊？我做的有点灰色的网站，不方便分享啊，我都是匿名的，服务器域名都在国外，有风险被抓。
