### ISSUE TITLE
app.go 报错 bindata目录被删除了

### ISSUE THREAD

**Issue by JssDream** [gaowei-space/markdown-blog#45]
app.go文件报错 internal/bindata目录被删除了

**Comment by gaowei-space** [comment]
可以贴下操作步骤吗？

**Comment by JssDream** [comment]
![image](https://github.com/gaowei-space/markdown-blog/assets/24471999/b8425e70-987d-4776-9478-802aa41451f5)
就是这个目录好像被你删了？？但是app.go里面没改，有引用

**Comment by gaowei-space** [comment]
> ![image](https://user-images.githubusercontent.com/24471999/261483394-b8425e70-987d-4776-9478-802aa41451f5.png) 就是这个目录好像被你删了？？但是app.go里面没改，有引用

你是要进行二次开发吗？如果是的话，可以在修改代码后执行 `make bindata` 或者 `make build`，如果是搭建博客的话，可以使用[二进制文件](https://github.com/gaowei-space/markdown-blog/releases)哈

**Comment by JssDream** [comment]
不是二次开发，就是拉下来看看，学习下。但是这不是报错了吗！压根不能执行

**Comment by gaowei-space** [comment]
> 不是二次开发，就是拉下来看看，学习下。但是这不是报错了吗！压根不能执行

执行前可以执行下 `make bindata` 生成下，再试试

**Comment by JssDream** [comment]
好的，我试试，刚开始学go
