### ISSUE TITLE
adguard插件会拦截chapter-fold.js文件，建议更改js名。

### ISSUE THREAD

**Issue by dianso** [gaowei-space/markdown-blog#46]
发现adguard会拦截一些请求，比如/static/js/chapter-fold.js这个文件，导致侧边栏点击无法展开。

应该是匹配到chapter*.js这种文件就会触发的。

adguard报错：

请求详细信息
状态:
GET
过滤状态：
已拦截
URL：
/static/js/chapter-fold.js
打开于新标签内
类型：
JavaScript
规则：
/js/chapter*.js
过滤器：

**Comment by gaowei-space** [comment]
> 发现adguard会拦截一些请求，比如/static/js/chapter-fold.js这个文件，导致侧边栏点击无法展开。
> 
> 应该是匹配到chapter*.js这种文件就会触发的。
> 
> adguard报错：
> 
> 请求详细信息 状态: GET 过滤状态： 已拦截 URL： /static/js/chapter-fold.js 打开于新标签内 类型： JavaScript 规则： /js/chapter*.js 过滤器：

ok
