### ISSUE TITLE
作者你好，请问如何限制侧边栏一个文件夹下展示的.md文件数量啊

### ISSUE THREAD

**Issue by dianso** [gaowei-space/markdown-blog#48]
作者你好，请问如何限制侧边栏一个文件夹下展示的.md文件数量啊

有些目录里面很多很长，我想让它只显示一部分，比如50篇，剩下的可以访问，但是不在侧边栏展示出来

**Comment by gaowei-space** [comment]
> 作者你好，请问如何限制侧边栏一个文件夹下展示的.md文件数量啊
> 
> 有些目录里面很多很长，我想让它只显示一部分，比如50篇，剩下的可以访问，但是不在侧边栏展示出来

创建子文件夹加以区分呢

**Comment by dianso** [comment]
> > 作者你好，请问如何限制侧边栏一个文件夹下展示的.md文件数量啊
> > 有些目录里面很多很长，我想让它只显示一部分，比如50篇，剩下的可以访问，但是不在侧边栏展示出来
> 
> 创建子文件夹加以区分呢

还有其他办法吗？

子文件夹我试了也有点乱。

我翻了翻代码，没找到哪里能修改数量

**Comment by gaowei-space** [comment]
> > > 作者你好，请问如何限制侧边栏一个文件夹下展示的.md文件数量啊
> > > 有些目录里面很多很长，我想让它只显示一部分，比如50篇，剩下的可以访问，但是不在侧边栏展示出来
> > 
> > 
> > 创建子文件夹加以区分呢
> 
> 还有其他办法吗？
> 
> 子文件夹我试了也有点乱。
> 
> 我翻了翻代码，没找到哪里能修改数量

嗯，目前的前后代码都是不支持的
