### ISSUE TITLE
为什么Fork 源码下来运行一直出现这个问题？

### ISSUE THREAD

**Issue by BigSmallBrain** [gaowei-space/markdown-blog#49]
2023-10-26 10:15:38|2.9805ms|500|GET|/|::1|0 B|0 B|error(template: layouts/layout.html:64:7: executing "layouts/layout.html" at <render>: wrong number of args for render: want 2 got 1)|

![image](https://github.com/gaowei-space/markdown-blog/assets/117590278/94144376-42e6-463e-8add-de25c50ee629)

**Comment by gaowei-space** [comment]
是不是升级了 iris 框架了呢？ layouts/layout.html ，64行，改为这样看看 :  {{ render "layouts/header.html" . }}

**Comment by gaowei-space** [comment]
> 2023-10-26 10:15:38|2.9805ms|500|GET|/|::1|0 B|0 B|error(template: layouts/layout.html:64:7: executing "layouts/layout.html" at : wrong number of args for render: want 2 got 1)|
> 
> ![image](https://user-images.githubusercontent.com/117590278/278193094-94144376-42e6-463e-8add-de25c50ee629.png)

是不是升级了 iris 框架了呢？ layouts/layout.html ，64行，改为这样看看 : {{ render "layouts/header.html" . }}

**Comment by BigSmallBrain** [comment]
![image](https://github.com/gaowei-space/markdown-blog/assets/117590278/7ea6663f-6ceb-4a12-8e97-4dddccd6f53b)
已经解决了 用了最新的iris上面三处全改问题解决 感谢大佬👍
