### ISSUE TITLE
如果目录能支持[toc]就好了

### ISSUE THREAD

**Issue by baoqihui** [gaowei-space/markdown-blog#5]
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/50536515/188404857-6a79ff68-43c7-46da-b6c6-6998a426025a.png">

**Comment by gaowei-space** [comment]
got，我看看

**Comment by gaowei-space** [comment]
@baoqihui  刚刚更新了 v0.0.5版本，已经支持 `toc` 语法了 ✌️
