### ISSUE TITLE
是否考虑支持公安备案

### ISSUE THREAD

**Issue by Egolas** [gaowei-space/markdown-blog#50]
现在已经很多地方要求除了icp备案还要挂公安备案了，有没有计划支持一下

**Comment by gaowei-space** [comment]
> 现在已经很多地方要求除了icp备案还要挂公安备案了，有没有计划支持一下

<img width="382" alt="image" src="https://github.com/gaowei-space/markdown-blog/assets/10205742/726782e8-0847-42ba-b1db-89cee45e0333">
新版本已支持

**Comment by Egolas** [comment]
> > 现在已经很多地方要求除了icp备案还要挂公安备案了，有没有计划支持一下
> 
> <img alt="image" width="382" src="https://user-images.githubusercontent.com/10205742/282234217-726782e8-0847-42ba-b1db-89cee45e0333.png"> 新版本已支持

ICP备案和公安备案是两个东西，ICP是工信部备案，公安备案是公安部的备案，网址分别为`https://beian.miit.gov.cn/` 和`https://beian.mps.gov.cn/#/`

**Comment by gaowei-space** [comment]
> > > 现在已经很多地方要求除了icp备案还要挂公安备案了，有没有计划支持一下
> > 
> > 
> > <img alt="image" width="382" src="https://user-images.githubusercontent.com/10205742/282234217-726782e8-0847-42ba-b1db-89cee45e0333.png"> 新版本已支持
> 
> ICP备案和公安备案是两个东西，ICP是工信部备案，公安备案是公安部的备案，网址分别为`https://beian.miit.gov.cn/` 和`https://beian.mps.gov.cn/#/`

哦哦哦，没仔细看
