### ISSUE TITLE
可以考虑将主题文件外置吗？单文件修改最基本的都需要重新编译。

### ISSUE THREAD

**Issue by dianso** [gaowei-space/markdown-blog#53]
可以考虑将主题文件外置吗？单文件修改最基本的都需要重新编译。

有些不太方便。

**Comment by gaowei-space** [comment]
> 可以考虑将主题文件外置吗？单文件修改最基本的都需要重新编译。
> 
> 有些不太方便。

精力有限，没有适配的打算噢
