### ISSUE TITLE
请问镜像是出什么问题了吗

### ISSUE THREAD

**Issue by chovYena** [gaowei-space/markdown-blog#55]
我使用docker 运行后 
容器是运行状态
容器没有任何日志
端口访问也是502

```sh
docker run -dit --rm --name=markdown-blog \
-p 5006:5006 \
-v $(pwd)/md:/md \
-v $(pwd)/cache:/cache \
willgao/markdown-blog:latest \
-t "倚窗听雨思徐行"
```
![image](https://github.com/gaowei-space/markdown-blog/assets/141610777/e265314d-36dd-493a-b6c9-2f7510384136)

**Comment by gaowei-space** [comment]
> 我使用docker 运行后 容器是运行状态 容器没有任何日志 端口访问也是502
> 
> ```shell
> docker run -dit --rm --name=markdown-blog \
> -p 5006:5006 \
> -v $(pwd)/md:/md \
> -v $(pwd)/cache:/cache \
> willgao/markdown-blog:latest \
> -t "倚窗听雨思徐行"
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/141610777/285358071-e265314d-36dd-493a-b6c9-2f7510384136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzUzNDYsIm5iZiI6MTcwMTEzNTA0NiwicGF0aCI6Ii8xNDE2MTA3NzcvMjg1MzU4MDcxLWUyNjUzMTRkLTM2ZGQtNDkzYS1iNmM5LTJmNzUxMDM4NDEzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQwMTMwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjMxNTMzYWUwYWQwMGU3ZmJkY2ViN2VmODIwMDVlN2ExYzFiYmIxMzVmZTRjMmYwNDM5YjBkYjczOTEyYjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IF3-cXOU9--LPiU5kTKLKa_zeQRhWnQT_4ZAJFZ4ACM)

没有复现你说的问题，我这边的执行步骤如下：

1. docker pull willgao/markdown-blog:latest
2. mkdir md && touch md/test.md && echo "### Hello World" > ./md/test.md
3. 执行启动
``` docker run -dit --rm --name=markdown-blog \
-p 5006:5006 \
-v $(pwd)/md:/md \
-v $(pwd)/cache:/cache \
willgao/markdown-blog:latest \
-t "倚窗听雨思徐行"```
4.  访问 127.0.0.1:5006 正常
![image](https://github.com/gaowei-space/markdown-blog/assets/10205742/0d85e029-3755-4867-b61e-d8f871af8562)

**Comment by gaowei-space** [comment]
> > 我使用docker 运行后 容器是运行状态 容器没有任何日志 端口访问也是502
> > ```shell
> > docker run -dit --rm --name=markdown-blog \
> > -p 5006:5006 \
> > -v $(pwd)/md:/md \
> > -v $(pwd)/cache:/cache \
> > willgao/markdown-blog:latest \
> > -t "倚窗听雨思徐行"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/141610777/285358071-e265314d-36dd-493a-b6c9-2f7510384136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzUzNDYsIm5iZiI6MTcwMTEzNTA0NiwicGF0aCI6Ii8xNDE2MTA3NzcvMjg1MzU4MDcxLWUyNjUzMTRkLTM2ZGQtNDkzYS1iNmM5LTJmNzUxMDM4NDEzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQwMTMwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjMxNTMzYWUwYWQwMGU3ZmJkY2ViN2VmODIwMDVlN2ExYzFiYmIxMzVmZTRjMmYwNDM5YjBkYjczOTEyYjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IF3-cXOU9--LPiU5kTKLKa_zeQRhWnQT_4ZAJFZ4ACM)
> 
> 没有复现你说的问题，我这边的执行步骤如下：
> 
> 1. docker pull willgao/markdown-blog:latest
> 2. mkdir md && touch md/test.md && echo "### Hello World" > ./md/test.md
> 3. 执行启动
> 
> ```
> -p 5006:5006 \
> -v $(pwd)/md:/md \
> -v $(pwd)/cache:/cache \
> willgao/markdown-blog:latest \
> -t "倚窗听雨思徐行"```
> 4.  访问 127.0.0.1:5006 正常
> ![image](https://github.com/gaowei-space/markdown-blog/assets/10205742/0d85e029-3755-4867-b61e-d8f871af8562)

**Comment by chovYena** [comment]
> > > 我使用docker 运行后 容器是运行状态 容器没有任何日志 端口访问也是502
> > > ```shell
> > > docker run -dit --rm --name=markdown-blog \
> > > -p 5006:5006 \
> > > -v $(pwd)/md:/md \
> > > -v $(pwd)/cache:/cache \
> > > willgao/markdown-blog:latest \
> > > -t "倚窗听雨思徐行"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![image](https://private-user-images.githubusercontent.com/141610777/285358071-e265314d-36dd-493a-b6c9-2f7510384136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzUzNDYsIm5iZiI6MTcwMTEzNTA0NiwicGF0aCI6Ii8xNDE2MTA3NzcvMjg1MzU4MDcxLWUyNjUzMTRkLTM2ZGQtNDkzYS1iNmM5LTJmNzUxMDM4NDEzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQwMTMwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjMxNTMzYWUwYWQwMGU3ZmJkY2ViN2VmODIwMDVlN2ExYzFiYmIxMzVmZTRjMmYwNDM5YjBkYjczOTEyYjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IF3-cXOU9--LPiU5kTKLKa_zeQRhWnQT_4ZAJFZ4ACM)
> > 
> > 
> > 没有复现你说的问题，我这边的执行步骤如下：
> > 
> > 1. docker pull willgao/markdown-blog:latest
> > 2. mkdir md && touch md/test.md && echo "### Hello World" > ./md/test.md
> > 3. 执行启动
> > 
> > ```
> > -p 5006:5006 \
> > -v $(pwd)/md:/md \
> > -v $(pwd)/cache:/cache \
> > willgao/markdown-blog:latest \
> > -t "倚窗听雨思徐行"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. 访问 127.0.0.1:5006 正常
> >    ![image](https://private-user-images.githubusercontent.com/10205742/286093975-0d85e029-3755-4867-b61e-d8f871af8562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjc2MjQsIm5iZiI6MTcwMTgyNzMyNCwicGF0aCI6Ii8xMDIwNTc0Mi8yODYwOTM5NzUtMGQ4NWUwMjktMzc1NS00ODY3LWI2MWUtZDhmODcxYWY4NTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAxNDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhY2U3N2M5MjA0YjJkMjI0MzE2OWMwNDBkNTQyYTMwYTIwNWUyYjg0OTJmZjNhMDUwNmU4YTE5NzQ3ZTM0ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EqxJzTHmub2PdGezS3HLGwpaznj7SjVryhwDz456mCg)

其实是个小问题，不过最好在文档记录一下，如果md目录超过三层并且在上层目录内没有md文件  你遍历目录和设置默认文件那块好像就报错了，具体啥原因我也没细看。后面 我改成两层就正常了

**Comment by gaowei-space** [comment]
> > > > 我使用docker 运行后 容器是运行状态 容器没有任何日志 端口访问也是502
> > > > ```shell
> > > > docker run -dit --rm --name=markdown-blog \
> > > > -p 5006:5006 \
> > > > -v $(pwd)/md:/md \
> > > > -v $(pwd)/cache:/cache \
> > > > willgao/markdown-blog:latest \
> > > > -t "倚窗听雨思徐行"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ![image](https://private-user-images.githubusercontent.com/141610777/285358071-e265314d-36dd-493a-b6c9-2f7510384136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzUzNDYsIm5iZiI6MTcwMTEzNTA0NiwicGF0aCI6Ii8xNDE2MTA3NzcvMjg1MzU4MDcxLWUyNjUzMTRkLTM2ZGQtNDkzYS1iNmM5LTJmNzUxMDM4NDEzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQwMTMwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjMxNTMzYWUwYWQwMGU3ZmJkY2ViN2VmODIwMDVlN2ExYzFiYmIxMzVmZTRjMmYwNDM5YjBkYjczOTEyYjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IF3-cXOU9--LPiU5kTKLKa_zeQRhWnQT_4ZAJFZ4ACM)
> > > 
> > > 
> > > 没有复现你说的问题，我这边的执行步骤如下：
> > > 
> > > 1. docker pull willgao/markdown-blog:latest
> > > 2. mkdir md && touch md/test.md && echo "### Hello World" > ./md/test.md
> > > 3. 执行启动
> > > 
> > > ```
> > > -p 5006:5006 \
> > > -v $(pwd)/md:/md \
> > > -v $(pwd)/cache:/cache \
> > > willgao/markdown-blog:latest \
> > > -t "倚窗听雨思徐行"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 4. 访问 127.0.0.1:5006 正常
> > >    ![image](https://private-user-images.githubusercontent.com/10205742/286093975-0d85e029-3755-4867-b61e-d8f871af8562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjc2MjQsIm5iZiI6MTcwMTgyNzMyNCwicGF0aCI6Ii8xMDIwNTc0Mi8yODYwOTM5NzUtMGQ4NWUwMjktMzc1NS00ODY3LWI2MWUtZDhmODcxYWY4NTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAxNDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhY2U3N2M5MjA0YjJkMjI0MzE2OWMwNDBkNTQyYTMwYTIwNWUyYjg0OTJmZjNhMDUwNmU4YTE5NzQ3ZTM0ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EqxJzTHmub2PdGezS3HLGwpaznj7SjVryhwDz456mCg)
> 
> 其实是个小问题，不过最好在文档记录一下，如果md目录超过三层并且在上层目录内没有md文件 你遍历目录和设置默认文件那块好像就报错了，具体啥原因我也没细看。后面 我改成两层就正常了

get
