### ISSUE TITLE
有人试过远端部署成功吗?

### ISSUE THREAD

**Issue by Alafun** [gaowei-space/markdown-blog#6]
我的服务器是阿里云,具体配置如下
![image](https://user-images.githubusercontent.com/78416589/200307738-8da07e10-ee9f-4bcc-9e8d-b8db0ffb23e7.png)
下载了版本 `markdown-blog-linux-amd64`
解压的时候报错如下:
![image](https://user-images.githubusercontent.com/78416589/200307909-ef2a55a6-6f91-4b2c-bff9-8e0583860b10.png)
运行`./markdown-blog web` 命令之后一直没有反应; 
看来之前关闭的issue, 尝试之后无果.

**Comment by gaowei-space** [comment]
加一下 -e dev 参数看看有没有什么错误输出。我的个人博客当前也是这么启动的，运行正常，http://blog.gaowei.tech

**Comment by gaowei-space** [comment]
@Alafun  从当前的日志信息来看应该启动成功了，你试试配置下nginx后访问 或者 阿里云服务器开放一下 5006 端口，然后通过IP:port 的方式访问看看

**Comment by Alafun** [comment]
> 通过IP:port 的方式访问看看

IP:PORT 可以访问nginx的 `index.html`

**Comment by Alafun** [comment]
![image](https://user-images.githubusercontent.com/78416589/202089345-ebd85034-1e48-411f-8aa2-abf7b03771bd.png)

>For systems using NGINX: You should now put your content in a location of your choice and edit the root configuration directive in the nginx configuration file /etc/nginx/nginx.conf.

**Comment by gaowei-space** [comment]
@Alafun 放开5006端口后，访问：http://服务器IP:5006，展示的nginx页面？🫣

**Comment by Alafun** [comment]
> 放开5006端口后，访问：http://服务器IP:5006，展示的nginx页面？

安全组添加5006 端口之后, 访问不了IP:5006

**Comment by gaowei-space** [comment]
@Alafun 

用该命令测试下，端口是否正确放通
```shell
wget 服务器IP:5006
```

Mac环境，如果端口正常放通，会输出以下响应
![image](https://user-images.githubusercontent.com/10205742/202438009-a5bfb4eb-bde4-4c28-9b87-f9b421a5c821.png)

**Comment by gaowei-space** [comment]
@Alafun  放通的端口协议记得选 tcp

**Comment by Alafun** [comment]
@gaowei-space 
![image](https://user-images.githubusercontent.com/78416589/202841920-949cae1d-5862-44cb-a8d9-f6ac09ee23c1.png)
这样对吗

**Comment by Alafun** [comment]
但是ping不通端口,wget一直链接超时

**Comment by gaowei-space** [comment]
@Alafun  如果没放通 ICMP协议 端口，ping 不通属于正常的；看你阿里云安全策略应该是没问题了，怀疑是服务器内还有限制防火墙限制，参考这边文章看看排查看看 http://www.kaixinit.com/centos/4838.html

**Comment by Alafun** [comment]
![image](https://user-images.githubusercontent.com/78416589/202859069-ee0420f9-12ea-4192-bd68-e07faf43d913.png)

**Comment by gaowei-space** [comment]
@Alafun  目前还是不行吗？系统内的防火墙停止 `systemctl stop firewalld` 了看看呢？

**Comment by gaowei-space** [comment]
下午更新支持了 docker 部署，如果云服务器已经安装了docker，部署起来会更加简单，可以试试

**Comment by Alafun** [comment]
昨天试了，第一次接触docker，成功跑了Wordpress，但是好像跑不起来markdown-blog（可以pull下来）

**Comment by gaowei-space** [comment]
@Alafun  尴尬了，应该和云服务有关系，不确定发布的`Docker`版本中是否包含你所用服务器的架构~

**Comment by gaowei-space** [comment]
@Alafun  issue 沟通比较费时，有时间看下邮件哈~

**Comment by Alafun** [comment]
> 

哦啦
